# Generated by Django 4.0.5 on 2022-06-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='descripton',
            new_name='description',
        ),
    ]
