# Generated by Django 4.0.4 on 2022-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('treats', 'treats'), ('drinks', 'drinks'), ('enterees', 'entrees'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
